// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4gu1CxSuAh-qNg_8bGL3zwOyca-65yck',
    appId: '1:348481477943:web:ac237809481fa6df4f0eb2',
    messagingSenderId: '348481477943',
    projectId: 'scorekeepermultiplayer',
    authDomain: 'scorekeepermultiplayer.firebaseapp.com',
    databaseURL: 'https://scorekeepermultiplayer-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scorekeepermultiplayer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuFwlKrC32JY0vB1r7-OxlbrQoS_vkG64',
    appId: '1:348481477943:android:3d75a8834239271c4f0eb2',
    messagingSenderId: '348481477943',
    projectId: 'scorekeepermultiplayer',
    databaseURL: 'https://scorekeepermultiplayer-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scorekeepermultiplayer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Ln9-mycBAJ4DxI6uhqavG4Kf1GtSyoI',
    appId: '1:348481477943:ios:69d9a2aa7456e0fd4f0eb2',
    messagingSenderId: '348481477943',
    projectId: 'scorekeepermultiplayer',
    databaseURL: 'https://scorekeepermultiplayer-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scorekeepermultiplayer.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Ln9-mycBAJ4DxI6uhqavG4Kf1GtSyoI',
    appId: '1:348481477943:ios:69d9a2aa7456e0fd4f0eb2',
    messagingSenderId: '348481477943',
    projectId: 'scorekeepermultiplayer',
    databaseURL: 'https://scorekeepermultiplayer-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scorekeepermultiplayer.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4gu1CxSuAh-qNg_8bGL3zwOyca-65yck',
    appId: '1:348481477943:web:bdf115d7958510604f0eb2',
    messagingSenderId: '348481477943',
    projectId: 'scorekeepermultiplayer',
    authDomain: 'scorekeepermultiplayer.firebaseapp.com',
    databaseURL: 'https://scorekeepermultiplayer-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scorekeepermultiplayer.firebasestorage.app',
  );
}
